function M = get_M(in1)
%GET_M
%    M = GET_M(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    10-Apr-2024 16:27:12

q2 = in1(2,:);
t2 = cos(q2);
t3 = t2.*(3.0./1.6e+1);
t4 = t3+5.3e+1./1.6e+2;
M = reshape([t2.*(3.0./8.0)+1.79e+2./1.6e+2,t4,t4,5.3e+1./1.6e+2],[2,2]);
