function C = get_C(in1,in2)
%GET_C
%    C = GET_C(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    10-Apr-2024 16:27:12

dq1 = in2(1,:);
dq2 = in2(2,:);
q2 = in1(2,:);
t2 = sin(q2);
C = reshape([dq2.*t2.*(-3.0./1.6e+1),dq1.*t2.*(3.0./1.6e+1),t2.*(dq1+dq2).*(-3.0./1.6e+1),0.0],[2,2]);
