function l_vect = get_l(in1)
%GET_L
%    L_VECT = GET_L(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    10-Apr-2024 16:26:21

q1 = in1(1,:);
q2 = in1(2,:);
t2 = cos(q1);
t3 = sin(q1);
t6 = sqrt(2.0);
t7 = atan(3.0./8.0);
t8 = atan(8.0./3.0);
t12 = sqrt(7.3e+1);
t4 = t2.*9.0;
t5 = t3.*2.4e+1;
t10 = q2+t7;
t11 = t3.*(3.0./4.0e+1);
t13 = -t7;
t9 = -t4;
t14 = q2+t13;
l_vect = [(t6.*sqrt(-t5+t9+4.1e+1))./4.0e+1;(t6.*sqrt(t5+t9+4.1e+1))./4.0e+1;(t6.*sqrt(t12.*sin(t10).*-3.0+4.1e+1))./4.0e+1;(t6.*sqrt(t12.*sin(t14).*3.0+4.1e+1))./4.0e+1;sqrt(-t11-t12.*cos(q1+q2-t8).*(3.0./8.0e+2)+(t12.*cos(t10))./4.0e+1+2.41e+2./8.0e+2);sqrt(t11+(t12.*cos(t14))./4.0e+1-t12.*cos(q1+q2+t8).*(3.0./8.0e+2)+2.41e+2./8.0e+2)];
